### PR TITLE
Ju 599 java21 migration --> master efs-submission-web

### PR DESCRIPTION
**Pull request by nghessen-ch**
JU-782 ready to deploy efs-submission-web into cidev. 
this pr contains all platform and dev changes. 
local testing complete and happy to proceed into cidev.

### CODE REVIEW

**Review by akunati-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Review by PhilipGlover — APPROVED** [review]
- I haven't run this code, but see many of these changes are for ECS and replacing Java library.
- skimmed through and nothing jumped out
- happy to trust testing carried out by other team

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
